apiVersion: v1
kind: Service
metadata:
  name: cacheclient-service
spec:
  type: LoadBalancer
  externalIPs:
  - 10.9.8.7
  selector:
    app: cache-client
  ports:
  - port: 8000
    targetPort: 5000
